# Generated by Django 4.2.7 on 2023-12-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_contacts_contact_text_alter_contacts_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_text',
            field=models.TextField(default='Cпасибо', verbose_name='Ваше сообщение'),
        ),
    ]
