# Generated by Django 4.2.7 on 2023-12-16 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_statusproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versions',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.statusproduct', verbose_name='наименование'),
        ),
    ]
