# Generated by Django 4.2.7 on 2023-12-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_numberversion_alter_statusproduct_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versions',
            name='number_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.numberversion', verbose_name='номер версии'),
        ),
    ]
