# Generated by Django 4.2.7 on 2023-12-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_versions_number_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberversion',
            name='status_name',
            field=models.IntegerField(unique=True, verbose_name='номер версии'),
        ),
    ]
